version: "3.7"

services:
  resilio:
    image: resilio/sync:latest
    container_name: resilio_sync
    ports:
    - 5454:8888
    restart: always
#    user: 1000:1000
    volumes:
      - ${DATA_FOLDER}:/mnt/sync
